language: python

env:
  - OGN_CONFIG_MODULE='config.test'

python:
  - 3.4
  - 3.5
  - 3.6

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

before_script:
  - flake8 tests ogn_test
  - psql -c 'CREATE DATABASE ogn_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d ogn_test

script:
  - nosetests --with-coverage --cover-package=ogn

  - pip install . --upgrade
  - python -c 'import ogn'

after_success:
  - coveralls
