language: python

env:
  - OGN_CONFIG_MODULE='config.test'

python:
  - 3.4

services:
  - postgresql

before_script:
  - flake8 tests ogn
  - sudo apt-get autoremove postgis*
  - sudo apt-get autoremove postgresql*
  - sudo apt-get install postgresql-9.3-postgis-2.1
  - psql -c 'CREATE DATABASE ogn_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d ogn_test

script:
  - nosetests --with-coverage --cover-package=ogn

  - pip install . --upgrade
  - python -c 'import ogn'

after_success:
  - coveralls
