language: python

env:
  - OGN_CONFIG_MODULE='config.test'

python:
  - 3.4
  - 3.5
  - 3.6

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

before_script:
  - flake8 tests ogn_test
  - psql -U postgres -c 'CREATE DATABASE ogn_test;'
  - psql -U postgres -c 'CREATE EXTENSION postgis;'
  - psql -U postgres -d ogn_test

script:
  - nosetests --with-coverage --cover-package=ogn

  - pip install . --upgrade
  - python -c 'import ogn'

after_success:
  - coveralls
